/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SumateRouteImport } from './routes/sumate'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as EmprendedoresIndexRouteImport } from './routes/emprendedores.index'
import { Route as EmprendedoresSlugRouteImport } from './routes/emprendedores.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SumateRoute = SumateRouteImport.update({
  id: '/sumate',
  path: '/sumate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprendedoresIndexRoute = EmprendedoresIndexRouteImport.update({
  id: '/emprendedores/',
  path: '/emprendedores/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmprendedoresSlugRoute = EmprendedoresSlugRouteImport.update({
  id: '/emprendedores/$slug',
  path: '/emprendedores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidad': typeof ComunidadRoute
  '/eventos': typeof EventosRoute
  '/radio': typeof RadioRoute
  '/sobre': typeof SobreRoute
  '/sumate': typeof SumateRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/emprendedores/$slug': typeof EmprendedoresSlugRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/emprendedores/': typeof EmprendedoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidad': typeof ComunidadRoute
  '/eventos': typeof EventosRoute
  '/radio': typeof RadioRoute
  '/sobre': typeof SobreRoute
  '/sumate': typeof SumateRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/emprendedores/$slug': typeof EmprendedoresSlugRoute
  '/categorias': typeof CategoriasIndexRoute
  '/emprendedores': typeof EmprendedoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/comunidad': typeof ComunidadRoute
  '/eventos': typeof EventosRoute
  '/radio': typeof RadioRoute
  '/sobre': typeof SobreRoute
  '/sumate': typeof SumateRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/emprendedores/$slug': typeof EmprendedoresSlugRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/emprendedores/': typeof EmprendedoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comunidad'
    | '/eventos'
    | '/radio'
    | '/sobre'
    | '/sumate'
    | '/panel'
    | '/emprendedores/$slug'
    | '/categorias/'
    | '/emprendedores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comunidad'
    | '/eventos'
    | '/radio'
    | '/sobre'
    | '/sumate'
    | '/panel'
    | '/emprendedores/$slug'
    | '/categorias'
    | '/emprendedores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/comunidad'
    | '/eventos'
    | '/radio'
    | '/sobre'
    | '/sumate'
    | '/_authenticated/panel'
    | '/emprendedores/$slug'
    | '/categorias/'
    | '/emprendedores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComunidadRoute: typeof ComunidadRoute
  EventosRoute: typeof EventosRoute
  RadioRoute: typeof RadioRoute
  SobreRoute: typeof SobreRoute
  SumateRoute: typeof SumateRoute
  EmprendedoresSlugRoute: typeof EmprendedoresSlugRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
  EmprendedoresIndexRoute: typeof EmprendedoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sumate': {
      id: '/sumate'
      path: '/sumate'
      fullPath: '/sumate'
      preLoaderRoute: typeof SumateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprendedores/': {
      id: '/emprendedores/'
      path: '/emprendedores'
      fullPath: '/emprendedores/'
      preLoaderRoute: typeof EmprendedoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emprendedores/$slug': {
      id: '/emprendedores/$slug'
      path: '/emprendedores/$slug'
      fullPath: '/emprendedores/$slug'
      preLoaderRoute: typeof EmprendedoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComunidadRoute: ComunidadRoute,
  EventosRoute: EventosRoute,
  RadioRoute: RadioRoute,
  SobreRoute: SobreRoute,
  SumateRoute: SumateRoute,
  EmprendedoresSlugRoute: EmprendedoresSlugRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
  EmprendedoresIndexRoute: EmprendedoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
